#!/bin/sh
RED='\033[0;36m'
BLUE='\033[0;35m'
GREEN='\033[0;32m'
BACK_GREEN='\033[0;42m'
BACK_ORANGE='\033[0;43m'
PURPLE='\033[0;35m'
ORANGE='\033[0;33m'
END='\033[0m'
var=1
##while true
##do
##	if [ -z $TOR_CHECK ]; then
  ##      	echo "${BLUE}           IP Address :${END}\n""${RED}|||||||||||||||||||||| ${END} ${RED}SOCKS.5-TORPROXY: ${END}\n${RED}||${END}${BACK_GREEN} [$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')]${END} ${RED}||\n|||||||||||||||||||||| ${END} ${BACK_ORANGE}[ NOT CONNECTED]${END}"
##		while [ "$var" -le 25 ]; do
##			var=$(( var + 1 ))
##			echo '\007'
##			sleep 0.1s
##		done
##		var=1
        	#for (( c=1; c<=100; c++ )); do; echo '\007'; sleep 0.01s; done
		#Uncomment the line above to make an Ascii Beep Sound
		#Compatible with linux, WSL and Android
##	else
  ##      	echo "${BLUE}          IP Address :${END}\n""${RED}||||||||||||||||||||||   ${END}${RED}SOCKS.5-TORPROXY: ${END}\n||${BACK_GREEN}$ [(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')] ${END}${RED}||\n|||||||||||||||||||||| ${END} ${BACK_GREEN}[ $TOR_CHECK ]${END}"
##	fi
##	sleep 2s
##done
TOR_CHECK=$(curl --socks5 localhost:9050 --socks5-hostname localhost:9050 -s https://check.torproject.org/ | cat | grep -m 1 Congratulations | xargs)

while true
do
	if [ -z $TOR_CHECK ]
	then
        	echo "${BLUE}      Network:${END}            ${RED}SOCKS.5-TORPROXY: ${END}"
        	echo "${RED}||||||||||||||||||||||  |||||||||||||||||||||||${END}"
        	echo "${RED}|| ${END}${BACK_GREEN}[$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')]${END} ${RED}||   ||${END} ${BACK_PURPLE}[ NOT CONNECTED ]${END} ${RED}||${END}"
        	echo "${RED}|||||||||||||||||||||| ${END}${RED} |||||||||||||||||||||||${END}"
	else
		echo "${BLUE}Network:${END}"
        	echo "${RED}||||||||||||||||||||| ${END} ${RED}SOCKS.5-TORPROXY: ${END}"
        	echo "${RED}||${END}${BACK_GREEN} [$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')]${END} ||"
        	echo "${RED}||||||||||||||||||||| ${END} ${BACK_GREEN}[ $TOR_CHECK ]${END}"
	fi
	sleep 2s
done
