#!/bin/sh
cd ~/script
~/script/gitpush
echo "\033[42;m ~/script git pull DONE \033[0m"
cd ~/code/ft_printf
~/script/gitpush
echo "\033[42;m ftprintf git pull DONE \033[0m"
cd ~/code/get_next_line
~/script/gitpush
echo "\033[42;m getnextline git pull DONE \033[0m"
cd ~/code/born2beroot
~/script/gitpush
echo "\033[42;m born2beroot git pull DONE \033[0m"
cd ~/code/msf
~/script/gitpush
echo "\033[42;m ~/code/msf git pull DONE \033[0m"
cd ~/code/leetsec_cursus
~/script/gitpush
echo "\033[42;m ~/code/leetsec_cursus git pull DONE \033[0m"
cd ~/code/so_long
~/script/gitpush
echo "\033[42;m ~/code/so_long git pull DONE \033[0m"
cd ~/code/apk_android
~/script/gitpush
echo "\033[42;m ~/code/apk_androidgit pull DONE \033[0m"
cd ~/code/blog_scrapper
~/script/gitpush
echo "\033[42;m ~/code/blog_scrapper git pull DONE \033[0m"
cd ~/code/hackathons-webpentest-challenge
~/script/gitpush
echo "\033[42;m ~/code/hackathons_webpentest_challange git pull DONE \033[0m"
cd ~/code/steganography
~/script/gitpush
echo "\033[42;m ~/code/blog_scrapper git pull DONE \033[0m"
cd ~/code/email_scrapper
~/script/gitpush
echo "\033[42;m ~/code/email_scrapper git pull DONE \033[0m"
cd ~/code/solong_tmp
~/script/gitpush
echo "\033[42;m ~/code/solong_tmp git pull DONE \033[0m"
cd ~/code/1337-log-time
~/script/gitpush
echo "\033[42;m ~/code/1337-log-time git pull DONE \033[0m"



